INSERT INTO [NvDB].[dbo].[Countries] ([Name], [TwoLetterCode], [ThreeLetterCode], [CreatedAt], [ValidCountry])
VALUES 
-- Continente: África
('Algeria', 'DZ', 'DZA', GETDATE(), 0),
('Angola', 'AO', 'AGO', GETDATE(), 0),
('Benin', 'BJ', 'BEN', GETDATE(), 0),
('Botswana', 'BW', 'BWA', GETDATE(), 0),
('Burkina Faso', 'BF', 'BFA', GETDATE(), 0),
('Burundi', 'BI', 'BDI', GETDATE(), 0),
('Cabo Verde', 'CV', 'CPV', GETDATE(), 0),
('Cameroon', 'CM', 'CMR', GETDATE(), 0),
('Chad', 'TD', 'TCD', GETDATE(), 0),
('Comoros', 'KM', 'COM', GETDATE(), 0),
('Congo (Congo-Brazzaville)', 'CG', 'COG', GETDATE(), 0),
('Côte d\Ivoire', 'CI', 'CIV', GETDATE(), 0),
('Djibouti', 'DJ', 'DJI', GETDATE(), 0),
('Egypt', 'EG', 'EGY', GETDATE(), 0),
('Equatorial Guinea', 'GQ', 'GNQ', GETDATE(), 0),
('Eswatini (fmr. "Swaziland")', 'SZ', 'SWZ', GETDATE(), 0),
('Ethiopia', 'ET', 'ETH', GETDATE(), 0),
('Gabon', 'GA', 'GAB', GETDATE(), 0),
('Gambia', 'GM', 'GMB', GETDATE(), 0),
('Ghana', 'GH', 'GHA', GETDATE(), 0),
('Guinea', 'GN', 'GIN', GETDATE(), 0),
('Guinea-Bissau', 'GW', 'GNB', GETDATE(), 0),
('Kenya', 'KE', 'KEN', GETDATE(), 0),
('Lesotho', 'LS', 'LSO', GETDATE(), 0),
('Liberia', 'LR', 'LBR', GETDATE(), 0),
('Libya', 'LY', 'LBY', GETDATE(), 0),
('Madagascar', 'MG', 'MDG', GETDATE(), 0),
('Malawi', 'MW', 'MWI', GETDATE(), 0),
('Mali', 'ML', 'MLI', GETDATE(), 0),
('Mauritania', 'MR', 'MRT', GETDATE(), 0),
('Mauritius', 'MU', 'MUS', GETDATE(), 0),
('Morocco', 'MA', 'MAR', GETDATE(), 0),
('Mozambique', 'MZ', 'MOZ', GETDATE(), 0),
('Namibia', 'NA', 'NAM', GETDATE(), 0),
('Niger', 'NE', 'NER', GETDATE(), 0),
('Nigeria', 'NG', 'NGA', GETDATE(), 0),
('Rwanda', 'RW', 'RWA', GETDATE(), 0),
('São Tomé and Príncipe', 'ST', 'STP', GETDATE(), 0),
('Senegal', 'SN', 'SEN', GETDATE(), 0),
('Seychelles', 'SC', 'SYC', GETDATE(), 0),
('Sierra Leone', 'SL', 'SLE', GETDATE(), 0),
('Somalia', 'SO', 'SOM', GETDATE(), 0),
('South Africa', 'ZA', 'ZAF', GETDATE(), 0),
('South Sudan', 'SS', 'SSD', GETDATE(), 0),
('Sudan', 'SD', 'SDN', GETDATE(), 0),
('Tanzania', 'TZ', 'TZA', GETDATE(), 0),
('Togo', 'TG', 'TGO', GETDATE(), 0),
('Tunisia', 'TN', 'TUN', GETDATE(), 0),
('Uganda', 'UG', 'UGA', GETDATE(), 0),
('Zambia', 'ZM', 'ZMB', GETDATE(), 0),
('Zimbabwe', 'ZW', 'ZWE', GETDATE(), 0),

-- Continente: América
('Argentina', 'AR', 'ARG', GETDATE(), 0),
('Bolivia', 'BO', 'BOL', GETDATE(), 0),
('Brazil', 'BR', 'BRA', GETDATE(), 0),
('Canada', 'CA', 'CAN', GETDATE(), 0),
('Chile', 'CL', 'CHL', GETDATE(), 0),
('Colombia', 'CO', 'COL', GETDATE(), 0),
('Cuba', 'CU', 'CUB', GETDATE(), 0),
('Ecuador', 'EC', 'ECU', GETDATE(), 0),
('Mexico', 'MX', 'MEX', GETDATE(), 0),
('Paraguay', 'PY', 'PRY', GETDATE(), 0),
('Peru', 'PE', 'PER', GETDATE(), 0),
('Uruguay', 'UY', 'URY', GETDATE(), 0),
('Venezuela', 'VE', 'VEN', GETDATE(), 0),

-- Continente: Ásia e Oceania
('Afghanistan', 'AF', 'AFG', GETDATE(), 0),
('Australia', 'AU', 'AUS', GETDATE(), 0),
('India', 'IN', 'IND', GETDATE(), 0),
('Indonesia', 'ID', 'IDN', GETDATE(), 0),
('Iran', 'IR', 'IRN', GETDATE(), 0),
('Iraq', 'IQ', 'IRQ', GETDATE(), 0),
('Israel', 'IL', 'ISR', GETDATE(), 0),
('Malaysia', 'MY', 'MYS', GETDATE(), 0),
('New Zealand', 'NZ', 'NZL', GETDATE(), 0),
('Pakistan', 'PK', 'PAK', GETDATE(), 0),
('Philippines', 'PH', 'PHL', GETDATE(), 0),
('Saudi Arabia', 'SA', 'SAU', GETDATE(), 0),
('Singapore', 'SG', 'SGP', GETDATE(), 0),
('South Korea', 'KR', 'KOR', GETDATE(), 0),
('Sri Lanka', 'LK', 'LKA', GETDATE(), 0),
('Thailand', 'TH', 'THA', GETDATE(), 0),
('Vietnam', 'VN', 'VNM', GETDATE(), 0),

-- Continente: Europa (faltantes da sua tabela)
('Belgium', 'BE', 'BEL', GETDATE(), 0),
('Sweden', 'SE', 'SWE', GETDATE(), 0),
('Norway', 'NO', 'NOR', GETDATE(), 0),
('Switzerland', 'CH', 'CHE', GETDATE(), 0),
('Netherlands', 'NL', 'NLD', GETDATE(), 0),
('Portugal', 'PT', 'PRT', GETDATE(), 0),
('Austria', 'AT', 'AUT', GETDATE(), 0);


-- Territórios Dependentes
('Puerto Rico', 'PR', 'PRI', GETDATE(), 0),
('Hong Kong', 'HK', 'HKG', GETDATE(), 0),
('Macau', 'MO', 'MAC', GETDATE(), 0),
('Greenland', 'GL', 'GRL', GETDATE(), 0),
('Guam', 'GU', 'GUM', GETDATE(), 0),
('American Samoa', 'AS', 'ASM', GETDATE(), 0),
('Virgin Islands (U.S.)', 'VI', 'VIR', GETDATE(), 0),
('Bermuda', 'BM', 'BMU', GETDATE(), 0),
('Falkland Islands', 'FK', 'FLK', GETDATE(), 0),
('Cayman Islands', 'KY', 'CYM', GETDATE(), 0),

-- Países com status disputado
('Taiwan', 'TW', 'TWN', GETDATE(), 0),
('Palestine', 'PS', 'PSE', GETDATE(), 0),
('Kosovo', 'XK', 'XKX', GETDATE(), 0),
('Western Sahara', 'EH', 'ESH', GETDATE(), 0),
('Northern Cyprus', 'NC', 'NCT', GETDATE(), 0),

-- Outros territórios ou regiões
('French Polynesia', 'PF', 'PYF', GETDATE(), 0),
('New Caledonia', 'NC', 'NCL', GETDATE(), 0),
('Aruba', 'AW', 'ABW', GETDATE(), 0),
('Montserrat', 'MS', 'MSR', GETDATE(), 0),
('Réunion', 'RE', 'REU', GETDATE(), 0),


('Unknown Country', 'XX', 'XXX', GETDATE(), 0);